/*Required SQL query*/
SELECT BROKER.name, COUNT(CUSTOMER.broker_id) AS countNumber
FROM BROKER LEFT JOIN CUSTOMER
on BROKER.id = CUSTOMER.broker_id
GROUP BY BROKER.name
ORDER BY countNumber ASC, BROKER.name ASC;



/*-----------------------Test Purpose------------------------*/
/*CREATE TABLE CUSTOMER (
    id int,
   	name varchar(255),
    amount int,
    broker_id int, 
  	CONSTRAINT cus_pkey PRIMARY KEY(id)
);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (1,'sam',3000,4);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (2,'john',4000,2);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (3,'mack',5000,2);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (4,'test',3000,3);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (5,'june',2000,3);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (6,'mike',4000,1);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (7,'annie',4000,2);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (8,'micheal',2000,1);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (9,'tom',2000,4);

INSERT INTO CUSTOMER(ID,NAME,AMOUNT,BROKER_ID)
VALUES (10,'jason',6000,4);



/*CREATE TABLE BROKER (
    id int,
   	name varchar(255),

  	CONSTRAINT cus_pkey PRIMARY KEY(id)
);

INSERT INTO BROKER(ID,NAME)
VALUES (1,'Ted');

INSERT INTO BROKER(ID,NAME)
VALUES (2,'Mark');

INSERT INTO BROKER(ID,NAME)
VALUES (3,'Aaron');

INSERT INTO BROKER(ID,NAME)
VALUES (4,'Luke');

Drop TABLE CUSTOMER*/